package io.github.ryanoviski.hestia.infrastructure.database;

import io.github.ryanoviski.hestia.infrastructure.migrations.MigrationRunner;import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.sql.*;import static org.assertj.core.api.Assertions.*;

class AttachmentMigrationTest {
 @TempDir Path directory;
 @Test void upgradesVersionThreePreservingTransactionsAndRunsOnce()throws Exception{ConnectionFactory f=factory();try(var c=f.openConnection()){execute(c,"/db/migrations/V001__initial_schema.sql");execute(c,"/db/migrations/V002__create_transactions.sql");execute(c,"/db/migrations/V003__create_financial_commitments.sql");c.createStatement().execute("CREATE TABLE schema_history(version INTEGER PRIMARY KEY,description TEXT NOT NULL,applied_at TEXT NOT NULL)");c.createStatement().execute("INSERT INTO schema_history VALUES(1,'v1','2026-01-01T00:00:00Z'),(2,'v2','2026-01-01T00:00:00Z'),(3,'v3','2026-01-01T00:00:00Z')");c.createStatement().execute("INSERT INTO households VALUES(1,'Família','2026-01-01T00:00:00Z','2026-01-01T00:00:00Z')");c.createStatement().execute("INSERT INTO profiles VALUES(1,1,'Ana','PERSON',NULL,1,'2026-01-01T00:00:00Z','2026-01-01T00:00:00Z')");c.createStatement().execute("INSERT INTO categories VALUES(1,NULL,'Salário','INCOME',NULL,NULL,1,'2026-01-01T00:00:00Z','2026-01-01T00:00:00Z')");c.createStatement().execute("INSERT INTO transactions(household_id,profile_id,category_id,transaction_type,description,amount_cents,reference_date,status,created_at,updated_at) VALUES(1,1,1,'INCOME','Salário',10000,'2026-01-01','PENDING','2026-01-01T00:00:00Z','2026-01-01T00:00:00Z')");}new MigrationRunner(f).migrate();new MigrationRunner(f).migrate();try(var c=f.openConnection()){assertThat(count(c,"SELECT COUNT(*) FROM schema_history WHERE version=4")).isEqualTo(1);assertThat(count(c,"SELECT COUNT(*) FROM transactions WHERE description='Salário'")).isEqualTo(1);assertThat(count(c,"SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='attachments'")).isEqualTo(1);}}
 @Test void enforcesExactlyOneTargetAndForeignKeys()throws Exception{ConnectionFactory f=factory();new DatabaseInitializer(f).initialize();try(var c=f.openConnection()){c.createStatement().execute("INSERT INTO profiles(household_id,name,profile_type,active,created_at,updated_at) VALUES(1,'Ana','PERSON',1,'2026-01-01T00:00:00Z','2026-01-01T00:00:00Z')");assertThatThrownBy(()->insert(c,null,null)).isInstanceOf(SQLException.class);assertThatThrownBy(()->insert(c,1L,1L)).isInstanceOf(SQLException.class);assertThatThrownBy(()->insert(c,null,999L)).isInstanceOf(SQLException.class);}}
 private void insert(Connection c,Long tx,Long profile)throws SQLException{try(var s=c.prepareStatement("INSERT INTO attachments(household_id,transaction_id,profile_id,document_type,original_filename,storage_key,media_type,file_extension,size_bytes,sha256,created_at,updated_at) VALUES(1,?,?, 'OTHER','x.pdf','household-1/x.pdf','application/pdf','pdf',1,?,'2026-01-01T00:00:00Z','2026-01-01T00:00:00Z')")){if(tx==null)s.setNull(1,Types.INTEGER);else s.setLong(1,tx);if(profile==null)s.setNull(2,Types.INTEGER);else s.setLong(2,profile);s.setString(3,"a".repeat(64));s.executeUpdate();}}
 private ConnectionFactory factory()throws Exception{Path db=directory.resolve("db/hestia.db");Files.createDirectories(db.getParent());return new ConnectionFactory(db);}private int count(Connection c,String sql)throws Exception{try(var r=c.createStatement().executeQuery(sql)){return r.getInt(1);}}private void execute(Connection c,String resource)throws Exception{try(var stream=getClass().getResourceAsStream(resource)){String sql=new String(stream.readAllBytes(),StandardCharsets.UTF_8);for(String statement:sql.lines().filter(line->!line.stripLeading().startsWith("--")).reduce("",(a,b)->a+b+'\n').split(";")){if(!statement.isBlank())c.createStatement().execute(statement);}}}
}
