package io.github.ryanoviski.hestia.infrastructure.database;

import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;
import java.nio.file.*;import java.sql.SQLException;import java.nio.charset.StandardCharsets;
import static org.assertj.core.api.Assertions.*;

class FinancialCommitmentMigrationTest {
 @TempDir Path directory;
 @Test void createsAllTablesIndexesAndUniqueConstraints()throws Exception{ConnectionFactory f=factory();new DatabaseInitializer(f).initialize();try(var c=f.openConnection()){assertThat(count(c,"SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name IN ('recurring_expenses','recurring_expense_occurrences','installment_plans','installments')")).isEqualTo(4);assertThat(count(c,"SELECT COUNT(*) FROM sqlite_master WHERE type='index' AND name IN ('idx_recurring_expenses_household_active','idx_recurring_occurrences_rule','idx_installment_plans_household','idx_installments_plan')")).isEqualTo(4);}}
 @Test void rejectsInvalidReferencesAndDuplicateOccurrence()throws Exception{ConnectionFactory f=factory();new DatabaseInitializer(f).initialize();try(var c=f.openConnection()){assertThatThrownBy(()->c.createStatement().execute("INSERT INTO recurring_expenses(household_id,profile_id,category_id,description,amount_cents,first_due_date,active,created_at,updated_at) VALUES(1,999,999,'X',100,'2026-01-01',1,'2026-01-01T00:00:00Z','2026-01-01T00:00:00Z')")).isInstanceOf(SQLException.class);}}
 @Test void secondInitializationDoesNotRepeatVersionThree()throws Exception{ConnectionFactory f=factory();new DatabaseInitializer(f).initialize();new DatabaseInitializer(f).initialize();try(var c=f.openConnection()){assertThat(count(c,"SELECT COUNT(*) FROM schema_history WHERE version=3")).isEqualTo(1);}}
 @Test void upgradesVersionTwoAndPreservesExistingTransactions()throws Exception{ConnectionFactory f=factory();try(var c=f.openConnection()){execute(c,"/db/migrations/V001__initial_schema.sql");execute(c,"/db/migrations/V002__create_transactions.sql");c.createStatement().execute("CREATE TABLE schema_history(version INTEGER PRIMARY KEY,description TEXT NOT NULL,applied_at TEXT NOT NULL)");c.createStatement().execute("INSERT INTO schema_history VALUES(1,'initial','2026-01-01T00:00:00Z'),(2,'transactions','2026-01-01T00:00:00Z')");c.createStatement().execute("INSERT INTO households VALUES(1,'Família','2026-01-01T00:00:00Z','2026-01-01T00:00:00Z')");c.createStatement().execute("INSERT INTO profiles VALUES(1,1,'Ana','PERSON',NULL,1,'2026-01-01T00:00:00Z','2026-01-01T00:00:00Z')");c.createStatement().execute("INSERT INTO categories VALUES(1,NULL,'Moradia','EXPENSE',NULL,NULL,1,'2026-01-01T00:00:00Z','2026-01-01T00:00:00Z')");c.createStatement().execute("INSERT INTO transactions(household_id,profile_id,category_id,transaction_type,description,amount_cents,reference_date,status,created_at,updated_at) VALUES(1,1,1,'EXPENSE','Existente',1000,'2026-01-01','PENDING','2026-01-01T00:00:00Z','2026-01-01T00:00:00Z')");}new io.github.ryanoviski.hestia.infrastructure.migrations.MigrationRunner(f).migrate();try(var c=f.openConnection()){assertThat(count(c,"SELECT COUNT(*) FROM schema_history")).isEqualTo(3);assertThat(count(c,"SELECT COUNT(*) FROM transactions WHERE description='Existente'")).isEqualTo(1);assertThat(count(c,"SELECT COUNT(*) FROM installment_plans")).isZero();}}
 private ConnectionFactory factory()throws Exception{Path db=directory.resolve("db").resolve("test.db");Files.createDirectories(db.getParent());return new ConnectionFactory(db);}private int count(java.sql.Connection c,String sql)throws Exception{try(var r=c.createStatement().executeQuery(sql)){return r.getInt(1);}}
 private void execute(java.sql.Connection c,String resource)throws Exception{try(var stream=getClass().getResourceAsStream(resource)){String sql=new String(stream.readAllBytes(),StandardCharsets.UTF_8);for(String statement:sql.lines().filter(line->!line.stripLeading().startsWith("--")).reduce("",(a,b)->a+b+'\n').split(";")){if(!statement.isBlank())c.createStatement().execute(statement);}}}
}
