package io.github.ryanoviski.hestia.presentation.controllers;

import io.github.ryanoviski.hestia.application.dto.TransactionFilter;
import io.github.ryanoviski.hestia.config.ApplicationContext;
import io.github.ryanoviski.hestia.domain.enums.*;
import io.github.ryanoviski.hestia.domain.models.*;
import io.github.ryanoviski.hestia.util.MoneyUtils;
import io.github.ryanoviski.hestia.presentation.components.DialogSupport;
import io.github.ryanoviski.hestia.presentation.components.ComboBoxSupport;
import javafx.fxml.FXML;import javafx.geometry.Pos;import javafx.scene.control.*;import javafx.scene.layout.*;
import java.time.*;import java.time.format.TextStyle;import java.util.Locale;

public final class CalendarController {
 @FXML private Label monthTitle,summary;@FXML private GridPane calendarGrid;@FXML private ComboBox<TransactionType>typeFilter;@FXML private ComboBox<TransactionStatus>statusFilter;@FXML private ComboBox<Profile>profileFilter;@FXML private ComboBox<Category>categoryFilter;@FXML private ComboBox<TransactionOrigin>originFilter;private ApplicationContext context;private YearMonth month=YearMonth.now();private static final Locale PT=Locale.forLanguageTag("pt-BR");
 public void configure(ApplicationContext c){context=c;ComboBoxSupport.configure(typeFilter,TransactionType::displayName);ComboBoxSupport.configure(statusFilter,s->s==null?"":switch(s){case PENDING->"Pendente";case SETTLED->"Concluída";case CANCELLED->"Cancelada";});ComboBoxSupport.profiles(profileFilter);ComboBoxSupport.categories(categoryFilter);ComboBoxSupport.configure(originFilter,TransactionOrigin::displayName);typeFilter.getItems().setAll(TransactionType.values());statusFilter.getItems().setAll(TransactionStatus.values());profileFilter.getItems().setAll(c.profileService().listProfiles());categoryFilter.getItems().setAll(c.categoryService().search(null,null,false));originFilter.getItems().setAll(TransactionOrigin.values());refresh();}
 @FXML private void previous(){month=month.minusMonths(1);refresh();}@FXML private void next(){month=month.plusMonths(1);refresh();}@FXML private void today(){month=YearMonth.now();refresh();}
 @FXML private void refresh(){if(context==null)return;var data=context.calendarService().load(month,new TransactionFilter(null,month,typeFilter.getValue(),statusFilter.getValue(),id(profileFilter.getValue()),id(categoryFilter.getValue()),false,true,originFilter.getValue()));monthTitle.setText(cap(month.getMonth().getDisplayName(TextStyle.FULL,PT))+" de "+month.getYear());var s=data.summary();summary.setText("Receitas previstas: "+MoneyUtils.format(s.expectedIncome())+"   Recebidas: "+MoneyUtils.format(s.receivedIncome())+"   Despesas pendentes: "+MoneyUtils.format(s.pendingExpenses())+"   Pagas: "+MoneyUtils.format(s.paidExpenses())+"   Vencidas: "+MoneyUtils.format(s.overdueExpenses())+"   Resultado projetado: "+MoneyUtils.format(s.projectedResult())+"   Realizado: "+MoneyUtils.format(s.realizedResult()));draw(data);}
 private void draw(io.github.ryanoviski.hestia.application.dto.CalendarMonth data){calendarGrid.getChildren().clear();calendarGrid.getColumnConstraints().clear();for(int i=0;i<7;i++){ColumnConstraints cc=new ColumnConstraints();cc.setPercentWidth(100d/7);calendarGrid.getColumnConstraints().add(cc);}String[] days={"Seg","Ter","Qua","Qui","Sex","Sáb","Dom"};for(int i=0;i<7;i++){Label l=new Label(days[i]);l.setMaxWidth(Double.MAX_VALUE);l.setAlignment(Pos.CENTER);l.getStyleClass().add("field-label");calendarGrid.add(l,i,0);}LocalDate first=month.atDay(1);LocalDate start=first.minusDays(first.getDayOfWeek().getValue()-1L);for(int index=0;index<42;index++){LocalDate date=start.plusDays(index);VBox cell=new VBox(3,new Label(Integer.toString(date.getDayOfMonth())));cell.getStyleClass().add("calendar-day");if(!YearMonth.from(date).equals(month))cell.getStyleClass().add("calendar-outside");if(date.equals(LocalDate.now()))cell.getStyleClass().add("calendar-today");var items=data.days().getOrDefault(date,java.util.List.of());for(int j=0;j<Math.min(3,items.size());j++){Transaction t=items.get(j);Label item=new Label((t.type()==TransactionType.INCOME?"+ ":"− ")+MoneyUtils.formatCents(t.amountCents())+" · "+(t.originDetails()==null?t.origin().displayName():t.originDetails()));item.setMaxWidth(Double.MAX_VALUE);item.setEllipsisString("…");item.getStyleClass().add("calendar-item");Tooltip.install(item,new Tooltip(t.description()));item.setOnMouseClicked(e->showItem(t));cell.getChildren().add(item);}if(items.size()>3)cell.getChildren().add(new Label("+ "+(items.size()-3)+" itens"));calendarGrid.add(cell,index%7,index/7+1);GridPane.setHgrow(cell,Priority.ALWAYS);GridPane.setVgrow(cell,Priority.ALWAYS);}}
 private void showItem(Transaction t){Alert a=new Alert(Alert.AlertType.INFORMATION);a.setTitle("Compromisso financeiro");a.setHeaderText(t.description());a.setContentText("Valor: "+MoneyUtils.formatCents(t.amountCents())+"\nSituação: "+t.status().displayName(t.type())+"\nOrigem: "+(t.originDetails()==null?t.origin().displayName():t.originDetails()));DialogSupport.prepare(a,calendarGrid,500,0);a.showAndWait();}
 private String cap(String s){return Character.toUpperCase(s.charAt(0))+s.substring(1);}private Long id(Profile p){return p==null?null:p.id();}private Long id(Category c){return c==null?null:c.id();}
}
