package io.github.ryanoviski.hestia.presentation.controllers;

import io.github.ryanoviski.hestia.application.dto.InstallmentPlanInput;
import io.github.ryanoviski.hestia.config.ApplicationContext;
import io.github.ryanoviski.hestia.domain.enums.CategoryType;
import io.github.ryanoviski.hestia.domain.exceptions.ValidationException;
import io.github.ryanoviski.hestia.domain.models.*;
import io.github.ryanoviski.hestia.util.MoneyUtils;
import javafx.fxml.FXML;import javafx.geometry.Insets;import javafx.geometry.Pos;import javafx.scene.control.*;import javafx.scene.layout.*;
import java.time.LocalDate;import java.time.format.DateTimeFormatter;

public final class InstallmentPlansController {
 private static final DateTimeFormatter DATE=DateTimeFormatter.ofPattern("dd/MM/yyyy");@FXML private VBox list;@FXML private Label emptyState;private ApplicationContext context;
 public void configure(ApplicationContext c){context=c;refresh();}private void refresh(){var items=context.installmentPlanService().list();list.getChildren().clear();items.forEach(i->list.getChildren().add(row(i)));emptyState.setVisible(items.isEmpty());emptyState.setManaged(items.isEmpty());if(items.isEmpty())list.getChildren().add(emptyState);}
 @FXML private void create(){Dialog<Void>d=new Dialog<>();d.setTitle("Nova compra parcelada");ButtonType save=new ButtonType("Gerar parcelas",ButtonBar.ButtonData.OK_DONE);d.getDialogPane().getButtonTypes().addAll(save,ButtonType.CANCEL);TextField description=new TextField(),amount=new TextField();Spinner<Integer>count=new Spinner<>(1,120,2);ComboBox<Profile>profile=new ComboBox<>();profile.getItems().setAll(context.profileService().listProfiles().stream().filter(Profile::active).toList());profile.getItems().stream().findFirst().ifPresent(profile::setValue);ComboBox<Category>category=new ComboBox<>();category.getItems().setAll(context.categoryService().search(CategoryType.EXPENSE,null,false));category.getItems().stream().findFirst().ifPresent(category::setValue);DatePicker first=new DatePicker(LocalDate.now());TextArea notes=new TextArea();Label error=new Label();error.getStyleClass().add("form-error");GridPane g=new GridPane();g.setHgap(10);g.setVgap(8);g.setPadding(new Insets(8));int r=0;add(g,r++,"Descrição",description);add(g,r++,"Valor total",amount);add(g,r++,"Quantidade",count);add(g,r++,"Perfil",profile);add(g,r++,"Categoria",category);add(g,r++,"Primeiro vencimento",first);add(g,r++,"Observações",notes);g.add(error,1,r);d.getDialogPane().setContent(g);d.getDialogPane().setPrefWidth(560);((Button)d.getDialogPane().lookupButton(save)).addEventFilter(javafx.event.ActionEvent.ACTION,e->{e.consume();try{context.installmentPlanService().create(new InstallmentPlanInput(description.getText(),MoneyUtils.parseBrazilian(amount.getText()),count.getValue(),profile.getValue()==null?0:profile.getValue().id(),category.getValue()==null?0:category.getValue().id(),first.getValue(),notes.getText()));d.close();refresh();}catch(ValidationException ex){error.setText(ex.getMessage());}});d.showAndWait();}
 private HBox row(InstallmentPlan p){VBox info=new VBox(4,new Label(p.description()),new Label(p.profileName()+" · "+p.categoryName()+" · "+p.installmentCount()+" parcelas"),new Label("Pagas: "+p.paidCount()+" · Pendentes: "+p.pendingCount()+" · Próximo: "+(p.nextDueDate()==null?"—":DATE.format(p.nextDueDate()))));Label status=new Label(p.calculatedStatus().displayName());status.getStyleClass().addAll("status-pill","status-pending");VBox money=new VBox(3,new Label(MoneyUtils.formatCents(p.totalAmountCents())),new Label("Pago "+MoneyUtils.formatCents(p.paidAmountCents())+" · restante "+MoneyUtils.formatCents(p.remainingAmountCents())));Region spacer=new Region();HBox.setHgrow(spacer,Priority.ALWAYS);Button details=button("Ver parcelas",()->details(p));Button cancel=button("Cancelar restantes",()->cancel(p));HBox row=new HBox(10,info,spacer,status,money,details,cancel);row.setAlignment(Pos.CENTER_LEFT);row.getStyleClass().add("transaction-row");return row;}
 private void details(InstallmentPlan p){StringBuilder text=new StringBuilder();for(var i:context.installmentPlanService().installments(p.id()))text.append(i.number()).append("/ ").append(p.installmentCount()).append(" · ").append(DATE.format(i.dueDate())).append(" · ").append(MoneyUtils.formatCents(i.plannedAmountCents())).append(" · ").append(i.status().displayName(io.github.ryanoviski.hestia.domain.enums.TransactionType.EXPENSE)).append('\n');Alert a=new Alert(Alert.AlertType.INFORMATION,text.toString(),ButtonType.OK);a.setHeaderText(p.description());a.setTitle("Parcelas");a.showAndWait();}
 private void cancel(InstallmentPlan p){Alert a=new Alert(Alert.AlertType.CONFIRMATION,"Somente parcelas atuais ou futuras ainda pendentes serão canceladas. Parcelas pagas serão preservadas.",ButtonType.CANCEL,ButtonType.OK);a.setHeaderText("Cancelar parcelas restantes");if(a.showAndWait().orElse(ButtonType.CANCEL)==ButtonType.OK){context.installmentPlanService().cancelRemaining(p.id());refresh();}}
 private Button button(String t,Runnable r){Button b=new Button(t);b.getStyleClass().add("table-action");b.setOnAction(e->r.run());return b;}private void add(GridPane g,int r,String l,Control c){g.add(new Label(l),0,r);c.setMaxWidth(Double.MAX_VALUE);g.add(c,1,r);GridPane.setHgrow(c,Priority.ALWAYS);}
}
