package io.github.ryanoviski.hestia.presentation.controllers;

import io.github.ryanoviski.hestia.application.services.BackupPreferencesService;import io.github.ryanoviski.hestia.config.ApplicationContext;import javafx.application.Platform;import javafx.fxml.FXML;import javafx.scene.control.*;import javafx.stage.*;import java.io.File;import java.nio.file.Path;import java.time.Instant;import java.util.Arrays;
import javafx.scene.layout.VBox;

public final class SettingsController {
 @FXML private CheckBox automaticEnabled;@FXML private TextField automaticDirectory;@FXML private Spinner<Integer>retention;@FXML private Label status;@FXML private ProgressIndicator progress;private ApplicationContext context;
 public void configure(ApplicationContext c){context=c;retention.setValueFactory(new SpinnerValueFactory.IntegerSpinnerValueFactory(1,100,10));var s=c.backupPreferencesService().load();automaticEnabled.setSelected(s.enabled());automaticDirectory.setText(s.directory());retention.getValueFactory().setValue(s.retention());status.setText("Último backup: "+(s.lastBackup()==null?"nunca":s.lastBackup())+" · "+s.lastResult());}
 @FXML private void createBackup(){FileChooser chooser=new FileChooser();chooser.setInitialFileName("hestia-backup.hestia-backup");File file=chooser.showSaveDialog(status.getScene().getWindow());if(file==null)return;CheckBox protect=new CheckBox("Proteger com senha AES-256");PasswordField password=new PasswordField(),confirmation=new PasswordField();VBox box=new VBox(8,protect,new Label("Senha"),password,new Label("Confirmar senha"),confirmation,new Label("A senha não será armazenada."));Alert dialog=new Alert(Alert.AlertType.CONFIRMATION);dialog.setHeaderText("Criar backup");dialog.getDialogPane().setContent(box);if(dialog.showAndWait().orElse(ButtonType.CANCEL)!=ButtonType.OK)return;if(protect.isSelected()&&(!password.getText().equals(confirmation.getText())||password.getText().isBlank())){message("As senhas não conferem.",true);return;}char[]secret=protect.isSelected()?password.getText().toCharArray():null;busy(true);context.backupService().createAsync(file.toPath(),secret).whenComplete((path,error)->{if(secret!=null)Arrays.fill(secret,'\0');Platform.runLater(()->{busy(false);message(error==null?"Backup criado em "+path:"Não foi possível criar o backup.",error!=null);});});}
 @FXML private void restoreBackup(){FileChooser chooser=new FileChooser();chooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("Backup Hestia","*.hestia-backup"));File file=chooser.showOpenDialog(status.getScene().getWindow());if(file==null)return;PasswordField password=new PasswordField();Alert confirmation=new Alert(Alert.AlertType.CONFIRMATION);confirmation.setHeaderText("Restaurar backup?");confirmation.setContentText("Os dados atuais serão substituídos após validação completa. Um backup de segurança será criado automaticamente. Informe a senha se o arquivo estiver protegido.");confirmation.getDialogPane().setExpandableContent(password);confirmation.getDialogPane().setExpanded(true);if(confirmation.showAndWait().orElse(ButtonType.CANCEL)!=ButtonType.OK)return;char[]secret=password.getText().isBlank()?null:password.getText().toCharArray();busy(true);java.util.concurrent.CompletableFuture.runAsync(()->context.backupService().restore(file.toPath(),secret)).whenComplete((v,error)->{if(secret!=null)Arrays.fill(secret,'\0');Platform.runLater(()->{busy(false);message(error==null?"Restauração concluída. Reinicie o Hestia.":"O backup não foi restaurado. Os dados anteriores foram preservados.",error!=null);});});}
 @FXML private void saveAutomatic(){if(automaticEnabled.isSelected()){Alert warning=new Alert(Alert.AlertType.CONFIRMATION,"Backups automáticos não usam senha nesta versão. Ativar mesmo assim?",ButtonType.CANCEL,ButtonType.OK);if(warning.showAndWait().orElse(ButtonType.CANCEL)!=ButtonType.OK)return;}context.backupPreferencesService().save(new BackupPreferencesService.Settings(automaticEnabled.isSelected(),automaticDirectory.getText().trim(),retention.getValue(),null,"Configuração salva"));message("Configuração automática salva.",false);}
 private void busy(boolean value){progress.setVisible(value);progress.setManaged(value);}private void message(String text,boolean error){status.setText(text);status.getStyleClass().removeAll("form-error","form-success");status.getStyleClass().add(error?"form-error":"form-success");}
}
