package io.github.ryanoviski.hestia.application.services;

import io.github.ryanoviski.hestia.application.dto.*;import io.github.ryanoviski.hestia.config.ApplicationPaths;import io.github.ryanoviski.hestia.domain.enums.*;import io.github.ryanoviski.hestia.domain.models.*;import io.github.ryanoviski.hestia.infrastructure.database.*;import io.github.ryanoviski.hestia.infrastructure.filesystem.*;import io.github.ryanoviski.hestia.infrastructure.repositories.*;import org.apache.pdfbox.pdmodel.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;import javax.imageio.ImageIO;import java.awt.image.BufferedImage;import java.math.BigDecimal;import java.nio.file.*;import java.time.*;import static org.assertj.core.api.Assertions.*;

class AttachmentBackupIntegrationTest {
 @TempDir Path directory;private ApplicationPaths paths;private ConnectionFactory connections;private AttachmentService service;private BackupService backups;private Profile profile;private Transaction income,expense;private SafeAttachmentStorage storage;private SqliteAttachmentRepository repository;
 @BeforeEach void setup()throws Exception{paths=ApplicationPaths.at(directory.resolve("hestia"));paths.createDirectories();connections=new ConnectionFactory(paths.databaseFile());new DatabaseInitializer(connections).initialize();var pr=new SqliteProfileRepository(connections);var cr=new SqliteCategoryRepository(connections);var tr=new SqliteTransactionRepository(connections);repository=new SqliteAttachmentRepository(connections);var clock=Clock.fixed(Instant.parse("2026-09-18T12:00:00Z"),ZoneOffset.UTC);var ps=new ProfileService(pr);var cs=new CategoryService(cr,pr);var ts=new TransactionService(tr,pr,cr,clock);profile=ps.createProfile("Ana",ProfileType.PERSON,"#123456");Category inc=cs.search(CategoryType.INCOME,null,false).getFirst(),exp=cs.search(CategoryType.EXPENSE,null,false).getFirst();income=ts.create(new TransactionInput(TransactionType.INCOME,"Salário",new BigDecimal("100"),profile.id(),inc.id(),LocalDate.of(2026,9,1),null,TransactionStatus.PENDING,null,null));expense=ts.create(new TransactionInput(TransactionType.EXPENSE,"Mercado",new BigDecimal("50"),profile.id(),exp.id(),LocalDate.of(2026,9,2),LocalDate.of(2026,9,2),TransactionStatus.PENDING,null,null));var validator=new FileValidationService();storage=new SafeAttachmentStorage(paths.attachmentsDirectory(),paths.temporaryDirectory());service=new AttachmentService(repository,pr,tr,storage,validator,clock);var prefs=new BackupPreferencesService(paths.dataDirectory());backups=new BackupService(paths,connections,repository,pr,storage,validator,prefs,clock);}
 @Test void importsPayslipReceiptProfileDocumentAndSeveralFiles()throws Exception{var payslip=service.importForTransaction(income.id(),DocumentType.PAYSLIP,null,pdf("holerite.pdf"));var receipt=service.importForTransaction(expense.id(),DocumentType.RECEIPT,null,image("cupom.png","png"));var general=service.importForProfile(profile.id(),DocumentType.OTHER,"Documento",image("identidade.jpg","jpg"));service.importForTransaction(expense.id(),DocumentType.RECEIPT,null,image("segundo.jpeg","jpg"));assertThat(service.search(AttachmentFilter.empty())).hasSize(4);assertThat(payslip.storageKey()).doesNotContain("holerite").startsWith("household-1/");assertThat(receipt.integrity()).isEqualTo(AttachmentIntegrity.AVAILABLE);assertThat(general.profileId()).isEqualTo(profile.id());}
 @Test void duplicateAndSpecialOriginalNamesGetDistinctPhysicalKeys()throws Exception{Path file=image("comprovante ç.png","png");var one=service.importForProfile(profile.id(),DocumentType.OTHER,null,file);var two=service.importForProfile(profile.id(),DocumentType.OTHER,null,file);assertThat(one.originalFilename()).isEqualTo("comprovante ç.png");assertThat(one.storageKey()).isNotEqualTo(two.storageKey());}
 @Test void detectsMissingModifiedOrphanAndProtectsStorage()throws Exception{var a=service.importForProfile(profile.id(),DocumentType.OTHER,null,image("doc.png","png"));assertThat(service.verify(a.id())).isEqualTo(AttachmentIntegrity.AVAILABLE);Files.writeString(service.file(a),"alterado");assertThat(service.verify(a.id())).isEqualTo(AttachmentIntegrity.MODIFIED);Files.delete(service.file(a));assertThat(service.verify(a.id())).isEqualTo(AttachmentIntegrity.MISSING);Path orphan=paths.attachmentsDirectory().resolve("household-1/orphan.pdf");Files.createDirectories(orphan.getParent());Files.writeString(orphan,"%PDF-1.4");assertThat(service.diagnose().orphanFiles()).contains("household-1/orphan.pdf");}
 @Test void exportsAndRemovesCoordinately()throws Exception{var a=service.importForProfile(profile.id(),DocumentType.OTHER,null,image("doc.png","png"));Path exported=directory.resolve("exported.png");service.export(a.id(),exported,false);assertThat(exported).hasSameBinaryContentAs(service.file(a));service.remove(a.id());assertThat(service.search(AttachmentFilter.empty())).isEmpty();assertThat(service.file(a)).doesNotExist();}
 @Test void readsImageAndRendersPdfWithoutLeakingResources()throws Exception{var preview=new DocumentPreviewService();Path pdf=pdf("preview.pdf");assertThat(preview.pdfPageCount(pdf)).isEqualTo(1);assertThat(preview.renderPdf(pdf,0,72)).isNotNull();assertThat(preview.loadImage(image("preview.png","png"),100,100)).isNotNull();Path bad=directory.resolve("bad.pdf");Files.writeString(bad,"%PDF-bad");assertThatThrownBy(()->preview.pdfPageCount(bad)).isInstanceOf(io.github.ryanoviski.hestia.domain.exceptions.ValidationException.class);}
 @Test void createsManifestedBackupWithDatabaseAndAttachmentsButNoLogsOrCache()throws Exception{service.importForProfile(profile.id(),DocumentType.OTHER,null,image("doc.png","png"));Files.writeString(paths.logsDirectory().resolve("private.log"),"secret");Files.writeString(paths.cacheDirectory().resolve("thumb.png"),"cache");Path backup=backups.create(directory.resolve("full.hestia-backup"),null);BackupManifest manifest=backups.inspect(backup,null);assertThat(manifest.schemaVersion()).isEqualTo(5);assertThat(manifest.attachments()).hasSize(1);assertThat(manifest.files()).extracting(BackupManifest.BackupFile::path).contains("database/hestia.db").noneMatch(p->p.contains("logs")||p.contains("cache"));}
 @Test void passwordBackupRejectsWrongPassword()throws Exception{Path backup=backups.create(directory.resolve("secure.hestia-backup"),"segredo".toCharArray());assertThat(backups.inspect(backup,"segredo".toCharArray()).formatVersion()).isEqualTo(1);assertThatThrownBy(()->backups.inspect(backup,"errada".toCharArray())).isInstanceOf(RuntimeException.class);}
 @Test void restoresDatabaseAndAttachmentsTogether()throws Exception{var a=service.importForProfile(profile.id(),DocumentType.OTHER,null,image("doc.png","png"));Path backup=backups.create(directory.resolve("restore.hestia-backup"),null);service.remove(a.id());assertThat(service.search(AttachmentFilter.empty())).isEmpty();backups.restore(backup,null);assertThat(query("SELECT COUNT(*) FROM attachments")).isEqualTo(1);var restored=repository.search(1,AttachmentFilter.empty()).getFirst();assertThat(storage.resolve(restored.storageKey())).exists();assertThat(Files.list(paths.backupsDirectory()).anyMatch(p->p.getFileName().toString().startsWith("pre-restore-"))).isTrue();}
 @Test void rejectsRenamedArbitraryAndCorruptedBackups()throws Exception{Path random=directory.resolve("random.hestia-backup");Files.writeString(random,"not zip");assertThatThrownBy(()->backups.inspect(random,null)).isInstanceOf(RuntimeException.class);Path valid=backups.create(directory.resolve("valid.hestia-backup"),null);byte[] bytes=Files.readAllBytes(valid);bytes[bytes.length/2]^=0x7f;Files.write(valid,bytes);assertThatThrownBy(()->backups.inspect(valid,null)).isInstanceOf(RuntimeException.class);}
 private int query(String sql)throws Exception{try(var c=connections.openConnection();var r=c.createStatement().executeQuery(sql)){return r.getInt(1);}}private Path pdf(String name)throws Exception{Path p=directory.resolve(name);try(PDDocument d=new PDDocument()){d.addPage(new PDPage());d.save(p.toFile());}return p;}private Path image(String name,String format)throws Exception{Path p=directory.resolve(name);ImageIO.write(new BufferedImage(3,3,BufferedImage.TYPE_INT_RGB),format,p.toFile());return p;}
}
