package io.github.ryanoviski.hestia.application.services;

import io.github.ryanoviski.hestia.application.dto.*;
import io.github.ryanoviski.hestia.domain.enums.*;
import io.github.ryanoviski.hestia.domain.exceptions.ValidationException;
import io.github.ryanoviski.hestia.domain.models.*;
import io.github.ryanoviski.hestia.infrastructure.database.*;
import io.github.ryanoviski.hestia.infrastructure.repositories.*;
import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;
import java.math.BigDecimal;import java.nio.file.*;import java.time.*;
import static org.assertj.core.api.Assertions.*;

class FinancialCommitmentIntegrationTest {
 @TempDir Path directory;private ConnectionFactory factory;private Profile profile;private Category expense,income;private RecurringExpenseService recurring;private InstallmentPlanService plans;private TransactionService transactions;private CalendarService calendar;private DashboardService dashboard;private Clock clock;private SqliteFinancialCommitmentRepository commitmentRepository;
 @BeforeEach void setup()throws Exception{Path db=directory.resolve("isolated/hestia.db");Files.createDirectories(db.getParent());factory=new ConnectionFactory(db);new DatabaseInitializer(factory).initialize();var pr=new SqliteProfileRepository(factory);var cr=new SqliteCategoryRepository(factory);var tr=new SqliteTransactionRepository(factory);commitmentRepository=new SqliteFinancialCommitmentRepository(factory);clock=Clock.fixed(Instant.parse("2026-01-15T12:00:00Z"),ZoneOffset.UTC);var ps=new ProfileService(pr);var cs=new CategoryService(cr,pr);profile=ps.createProfile("Ana",ProfileType.PERSON,"#123456");expense=cs.search(CategoryType.EXPENSE,null,false).getFirst();income=cs.search(CategoryType.INCOME,null,false).getFirst();recurring=new RecurringExpenseService(commitmentRepository,pr,cr,clock);plans=new InstallmentPlanService(commitmentRepository,pr,cr,clock);transactions=new TransactionService(tr,pr,cr,clock);calendar=new CalendarService(tr,pr,recurring,clock);dashboard=new DashboardService(tr,pr,clock);}
 @Test void createsMonthlyRuleThroughHorizonAndIsIdempotent()throws Exception{RecurringExpense rule=recurring.create(rule("Aluguel","1500",LocalDate.of(2026,1,31),null,true));assertThat(rule.id()).isNotNull();assertThat(count("SELECT COUNT(*) FROM recurring_expense_occurrences")).isEqualTo(13);recurring.ensureGeneratedThrough(YearMonth.of(2027,1));assertThat(count("SELECT COUNT(*) FROM recurring_expense_occurrences")).isEqualTo(13);var items=transactions.search(new TransactionFilter(null,null,null,null,null,null,false,false,TransactionOrigin.RECURRING));assertThat(items).hasSize(13);assertThat(items.get(1).dueDate()).isIn(LocalDate.of(2026,2,28),LocalDate.of(2026,12,31));}
 @Test void generatesOnDemandAndHonorsEndDate()throws Exception{recurring.create(rule("Escola","900",LocalDate.of(2026,1,10),LocalDate.of(2026,3,31),true));recurring.ensureGeneratedThrough(YearMonth.of(2028,1));assertThat(count("SELECT COUNT(*) FROM recurring_expense_occurrences")).isEqualTo(3);}
 @Test void rejectsBadRecurringInputs(){assertThatThrownBy(()->recurring.create(rule("X","10",LocalDate.of(2026,2,1),LocalDate.of(2026,1,1),true))).isInstanceOf(ValidationException.class).hasMessageContaining("data final");assertThatThrownBy(()->recurring.create(new RecurringExpenseInput("X",BigDecimal.ZERO,profile.id(),expense.id(),LocalDate.now(clock),null,null,true))).isInstanceOf(ValidationException.class);assertThatThrownBy(()->recurring.create(new RecurringExpenseInput("X",BigDecimal.TEN,profile.id(),income.id(),LocalDate.now(clock),null,null,true))).isInstanceOf(ValidationException.class).hasMessageContaining("despesa");}
 @Test void individualEditMarksCustomizedAndRuleUpdatePreservesIt()throws Exception{RecurringExpense rule=recurring.create(rule("Energia","200",LocalDate.of(2026,1,20),null,true));var march=transactions.search(new TransactionFilter(null,YearMonth.of(2026,3),null,null,null,null,false,false,TransactionOrigin.RECURRING)).getFirst();transactions.update(march.id(),new TransactionInput(TransactionType.EXPENSE,"Energia março",new BigDecimal("237.45"),profile.id(),expense.id(),march.referenceDate(),march.dueDate(),TransactionStatus.PENDING,null,"medição real"));recurring.update(rule.id(),rule("Energia","250",LocalDate.of(2026,1,20),null,true));assertThat(transactions.find(march.id()).amountCents()).isEqualTo(23745);assertThat(count("SELECT customized FROM recurring_expense_occurrences WHERE transaction_id="+march.id())).isEqualTo(1);}
 @Test void deactivationOptionCancelsOnlyFuturePendingNonCustomized()throws Exception{RecurringExpense rule=recurring.create(rule("Academia","100",LocalDate.of(2026,1,20),null,true));var jan=month(2026,1);var feb=month(2026,2);var mar=month(2026,3);transactions.settle(feb.id(),LocalDate.of(2026,2,20));transactions.update(mar.id(),inputFor(mar,"110"));recurring.setActive(rule.id(),false,true);assertThat(transactions.find(jan.id()).status()).isEqualTo(TransactionStatus.CANCELLED);assertThat(transactions.find(feb.id()).status()).isEqualTo(TransactionStatus.SETTLED);assertThat(transactions.find(mar.id()).status()).isEqualTo(TransactionStatus.PENDING);}
 @Test void createsExactInstallmentsWithStableDatesAndOrigin()throws Exception{InstallmentPlan plan=plans.create(plan("Televisão","100",3,LocalDate.of(2026,1,31)));var items=plans.installments(plan.id());assertThat(items).extracting(Installment::plannedAmountCents).containsExactly(3334L,3333L,3333L);assertThat(items).extracting(Installment::dueDate).containsExactly(LocalDate.of(2026,1,31),LocalDate.of(2026,2,28),LocalDate.of(2026,3,31));assertThat(transactions.find(items.get(1).transactionId()).origin()).isEqualTo(TransactionOrigin.INSTALLMENT);assertThat(transactions.find(items.get(1).transactionId()).originDetails()).isEqualTo("Parcela 2 de 3");}
 @Test void rejectsInvalidInstallmentRules(){assertThatThrownBy(()->plans.create(plan("X","100",0,LocalDate.now(clock)))).isInstanceOf(ValidationException.class);assertThatThrownBy(()->plans.create(plan("X","100",121,LocalDate.now(clock)))).isInstanceOf(ValidationException.class);}
 @Test void settlesReopensAndCancelsRemainingWhilePreservingPaid()throws Exception{InstallmentPlan plan=plans.create(plan("Notebook","300",3,LocalDate.of(2026,1,15)));var items=plans.installments(plan.id());transactions.settle(items.getFirst().transactionId(),LocalDate.now(clock));transactions.reopen(items.getFirst().transactionId());transactions.settle(items.getFirst().transactionId(),LocalDate.now(clock));plans.cancelRemaining(plan.id());var after=plans.installments(plan.id());assertThat(after).extracting(Installment::status).containsExactly(TransactionStatus.SETTLED,TransactionStatus.CANCELLED,TransactionStatus.CANCELLED);assertThat(plans.list().getFirst().calculatedStatus()).isEqualTo(InstallmentPlanStatus.PARTIALLY_CANCELLED);}
 @Test void installmentValueAndTypeAreProtected(){var item=plans.installments(plans.create(plan("Mesa","200",2,LocalDate.now(clock))).id()).getFirst();var tx=transactions.find(item.transactionId());assertThatThrownBy(()->transactions.update(tx.id(),new TransactionInput(TransactionType.EXPENSE,tx.description(),new BigDecimal("99"),profile.id(),expense.id(),tx.referenceDate(),tx.dueDate(),tx.status(),null,null))).isInstanceOf(ValidationException.class).hasMessageContaining("valor");}
 @Test void dashboardCountsGeneratedTransactionsOnlyOnce(){recurring.create(rule("Aluguel","1000",LocalDate.of(2026,1,20),LocalDate.of(2026,1,31),true));plans.create(plan("Móvel","300",3,LocalDate.of(2026,1,25)));var s=dashboard.summary(YearMonth.of(2026,1));assertThat(s.pendingExpenses()).isEqualByComparingTo("1100");}
 @Test void calendarUsesDueDateFallbackFiltersAndGeneratesFuture(){transactions.create(new TransactionInput(TransactionType.INCOME,"Receita",new BigDecimal("50"),profile.id(),income.id(),LocalDate.of(2026,4,5),null,TransactionStatus.PENDING,null,null));recurring.create(rule("Internet","80",LocalDate.of(2026,1,10),null,true));var result=calendar.load(YearMonth.of(2026,4),new TransactionFilter(null,null,null,null,null,null,false,true,null));assertThat(result.days()).containsKeys(LocalDate.of(2026,4,5),LocalDate.of(2026,4,10));var filtered=calendar.load(YearMonth.of(2026,4),new TransactionFilter(null,null,TransactionType.EXPENSE,null,null,null,false,true,TransactionOrigin.RECURRING));assertThat(filtered.days().values().stream().flatMap(java.util.Collection::stream)).allMatch(t->t.origin()==TransactionOrigin.RECURRING);}
 @Test void rollsBackWholePlanWhenOneInstallmentFails()throws Exception{Instant now=Instant.now(clock);var plan=new InstallmentPlan(null,1,profile.id(),expense.id(),"Falha",200,2,LocalDate.of(2026,1,20),true,null,now,now,null,null,0,2,0,0,200,LocalDate.of(2026,1,20));var duplicate=java.util.List.of(new GeneratedExpense(YearMonth.of(2026,1),1,100,LocalDate.of(2026,1,20),"Falha 1",null),new GeneratedExpense(YearMonth.of(2026,2),1,100,LocalDate.of(2026,2,20),"Falha 2",null));assertThatThrownBy(()->commitmentRepository.createInstallmentPlan(plan,duplicate)).isInstanceOf(DatabaseException.class);assertThat(count("SELECT COUNT(*) FROM installment_plans")).isZero();assertThat(count("SELECT COUNT(*) FROM transactions")).isZero();}
 private RecurringExpenseInput rule(String d,String amount,LocalDate first,LocalDate end,boolean active){return new RecurringExpenseInput(d,new BigDecimal(amount),profile.id(),expense.id(),first,end,null,active);}private InstallmentPlanInput plan(String d,String amount,int count,LocalDate first){return new InstallmentPlanInput(d,new BigDecimal(amount),count,profile.id(),expense.id(),first,null);}private Transaction month(int y,int m){return transactions.search(new TransactionFilter(null,YearMonth.of(y,m),null,null,null,null,false,false,TransactionOrigin.RECURRING)).getFirst();}private TransactionInput inputFor(Transaction t,String amount){return new TransactionInput(t.type(),t.description(),new BigDecimal(amount),t.profileId(),t.categoryId(),t.referenceDate(),t.dueDate(),t.status(),t.settlementDate(),t.notes());}private int count(String sql)throws Exception{try(var c=factory.openConnection();var r=c.createStatement().executeQuery(sql)){return r.getInt(1);}}
}
