package io.github.ryanoviski.hestia.application.services;

import io.github.ryanoviski.hestia.application.dto.*;import io.github.ryanoviski.hestia.application.repositories.*;
import io.github.ryanoviski.hestia.domain.enums.*;import io.github.ryanoviski.hestia.domain.exceptions.ValidationException;import io.github.ryanoviski.hestia.domain.models.Attachment;
import io.github.ryanoviski.hestia.infrastructure.filesystem.*;
import java.awt.Desktop;import java.io.IOException;import java.nio.file.*;import java.time.*;import java.util.*;import java.util.concurrent.CompletableFuture;import java.util.stream.Stream;

public final class AttachmentService {
 private final AttachmentRepository repository;private final ProfileRepository profiles;private final TransactionRepository transactions;private final SafeAttachmentStorage storage;private final FileValidationService validator;private final Clock clock;
 public AttachmentService(AttachmentRepository repository,ProfileRepository profiles,TransactionRepository transactions,SafeAttachmentStorage storage,FileValidationService validator,Clock clock){this.repository=repository;this.profiles=profiles;this.transactions=transactions;this.storage=storage;this.validator=validator;this.clock=clock;}
 public Attachment importForTransaction(long transactionId,DocumentType type,String description,Path source){long household=profiles.findDefaultHouseholdId();transactions.findById(transactionId,household).orElseThrow(()->new ValidationException("Movimentação não encontrada."));return importFile(household,transactionId,null,type,description,source);}
 public Attachment importForProfile(long profileId,DocumentType type,String description,Path source){long household=profiles.findDefaultHouseholdId();var profile=profiles.findById(profileId).orElseThrow(()->new ValidationException("Perfil não encontrado."));if(profile.householdId()!=household)throw new ValidationException("Perfil inválido para este grupo.");return importFile(household,null,profileId,type,description,source);}
 public List<Attachment> search(AttachmentFilter filter){long household=profiles.findDefaultHouseholdId();return repository.search(household,filter).stream().map(this::withIntegrity).filter(a->filter.integrity()==null||a.integrity()==filter.integrity()).toList();}
 public Attachment find(long id){return withIntegrity(repository.findById(profiles.findDefaultHouseholdId(),id).orElseThrow(()->new ValidationException("Documento não encontrado.")));}
 public Path file(Attachment attachment){return storage.resolve(attachment.storageKey());}
 public AttachmentIntegrity verify(long id){return find(id).integrity();}
 public Path export(long id,Path destination,boolean overwrite){Attachment a=find(id);requireAvailable(a);try{if(Files.exists(destination)&&!overwrite)throw new ValidationException("Já existe um arquivo no destino.");Path parent=destination.toAbsolutePath().normalize().getParent();if(parent!=null)Files.createDirectories(parent);return Files.copy(file(a),destination,overwrite?new CopyOption[]{StandardCopyOption.REPLACE_EXISTING}:new CopyOption[]{});}catch(IOException e){throw new ValidationException("Não foi possível exportar a cópia.");}}
 public CompletableFuture<Void> openExternal(long id){Attachment a=find(id);requireAvailable(a);if(!Desktop.isDesktopSupported())return CompletableFuture.failedFuture(new ValidationException("Abertura externa não está disponível neste sistema."));return CompletableFuture.runAsync(()->{try{Desktop.getDesktop().open(file(a).toFile());}catch(IOException e){throw new ValidationException("Nenhum aplicativo compatível conseguiu abrir o arquivo.");}});}
 public void remove(long id){long household=profiles.findDefaultHouseholdId();Attachment a=repository.findById(household,id).orElseThrow(()->new ValidationException("Documento não encontrado."));Path original=storage.resolve(a.storageKey()),quarantine=null;try{if(Files.exists(original,LinkOption.NOFOLLOW_LINKS))quarantine=storage.quarantine(original);repository.delete(household,id);if(quarantine!=null)Files.deleteIfExists(quarantine);}catch(Exception e){if(quarantine!=null)try{storage.restoreQuarantine(quarantine,a.storageKey());}catch(IOException ignored){}if(e instanceof RuntimeException runtime)throw runtime;throw new ValidationException("Não foi possível remover o documento.");}}
 public StorageDiagnostic diagnose(){long household=profiles.findDefaultHouseholdId();List<Attachment>all=repository.search(household,AttachmentFilter.empty());List<Long>missing=all.stream().filter(a->!Files.exists(storage.resolve(a.storageKey()))).map(Attachment::id).toList();Set<String>known=new HashSet<>(repository.storageKeys(household));List<String>orphans=new ArrayList<>();try(Stream<Path>paths=Files.exists(storage.root())?Files.walk(storage.root()):Stream.empty()){paths.filter(Files::isRegularFile).forEach(path->{String key=storage.root().relativize(path).toString().replace('\\','/');if(!known.contains(key))orphans.add(key);});}catch(IOException e){throw new ValidationException("Não foi possível diagnosticar o armazenamento.");}return new StorageDiagnostic(missing,List.copyOf(orphans),List.of());}
 private Attachment importFile(long household,Long transaction,Long profile,DocumentType type,String description,Path source){if(type==null)throw new ValidationException("Selecione o tipo do documento.");String desc=description==null||description.isBlank()?null:description.trim();if(desc!=null&&desc.length()>300)throw new ValidationException("A descrição deve ter no máximo 300 caracteres.");ValidatedFile validated=validator.validate(source);Path temporary=null,stored=null;String key=storage.newStorageKey(household,validated.extension(),clock);try{temporary=storage.createTemporaryCopy(source);ValidatedFile copied=validator.validate(temporary);if(!validated.sha256().equals(copied.sha256())||validated.sizeBytes()!=copied.sizeBytes())throw new IOException("Copied file differs");stored=storage.store(temporary,key);Instant now=Instant.now(clock);String original=source.getFileName().toString().replaceAll("[\\p{Cntrl}]","_");return repository.insert(new Attachment(null,household,transaction,profile,type,desc,original,key,validated.mediaType(),validated.extension(),validated.sizeBytes(),validated.sha256(),now,now,null,null,null,AttachmentIntegrity.AVAILABLE));}catch(Exception e){try{if(temporary!=null)Files.deleteIfExists(temporary);if(stored!=null)Files.deleteIfExists(stored);}catch(IOException ignored){}if(e instanceof RuntimeException runtime)throw runtime;throw new ValidationException("Não foi possível importar o documento.");}}
 private Attachment withIntegrity(Attachment a){AttachmentIntegrity state;try{Path p=storage.resolve(a.storageKey());if(!Files.isRegularFile(p,LinkOption.NOFOLLOW_LINKS))state=AttachmentIntegrity.MISSING;else if(Files.size(p)!=a.sizeBytes()||!validator.sha256(p).equals(a.sha256()))state=AttachmentIntegrity.MODIFIED;else{ValidatedFile v=validator.validate(p);state=v.mediaType().equals(a.mediaType())?AttachmentIntegrity.AVAILABLE:AttachmentIntegrity.INVALID;}}catch(Exception e){state=AttachmentIntegrity.INVALID;}return new Attachment(a.id(),a.householdId(),a.transactionId(),a.profileId(),a.documentType(),a.description(),a.originalFilename(),a.storageKey(),a.mediaType(),a.fileExtension(),a.sizeBytes(),a.sha256(),a.createdAt(),a.updatedAt(),a.profileName(),a.transactionDescription(),a.transactionType(),state);}
 private void requireAvailable(Attachment a){if(a.integrity()!=AttachmentIntegrity.AVAILABLE)throw new ValidationException("O documento não está disponível ou foi alterado.");}
}
