package io.github.ryanoviski.hestia.application.services;

import com.fasterxml.jackson.databind.ObjectMapper;import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import io.github.ryanoviski.hestia.application.dto.*;import io.github.ryanoviski.hestia.application.repositories.*;import io.github.ryanoviski.hestia.config.ApplicationPaths;import io.github.ryanoviski.hestia.domain.exceptions.ValidationException;import io.github.ryanoviski.hestia.infrastructure.database.*;import io.github.ryanoviski.hestia.infrastructure.filesystem.*;
import net.lingala.zip4j.ZipFile;import net.lingala.zip4j.model.*;import net.lingala.zip4j.model.enums.*;
import java.io.*;import java.nio.file.*;import java.sql.*;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;import java.util.concurrent.CompletableFuture;import java.util.stream.Stream;

public final class BackupService {
 public static final int FORMAT_VERSION=1;private final ApplicationPaths paths;private final ConnectionFactory connections;private final AttachmentRepository attachments;private final ProfileRepository profiles;private final SafeAttachmentStorage storage;private final FileValidationService hashes;private final BackupPreferencesService preferences;private final ObjectMapper json=new ObjectMapper().registerModule(new JavaTimeModule());private final Clock clock;
 public BackupService(ApplicationPaths paths,ConnectionFactory connections,AttachmentRepository attachments,ProfileRepository profiles,SafeAttachmentStorage storage,FileValidationService hashes,BackupPreferencesService preferences,Clock clock){this.paths=paths;this.connections=connections;this.attachments=attachments;this.profiles=profiles;this.storage=storage;this.hashes=hashes;this.preferences=preferences;this.clock=clock;}
 public CompletableFuture<Path> createAsync(Path destination,char[] password){char[] copy=password==null?null:password.clone();return CompletableFuture.supplyAsync(()->{try{return create(destination,copy);}finally{if(copy!=null)Arrays.fill(copy,'\0');}});}
 public Path create(Path destination,char[] password){if(destination==null)throw new ValidationException("Escolha o destino do backup.");Path finalPath=destination.toAbsolutePath().normalize();if(!finalPath.getFileName().toString().endsWith(".hestia-backup"))finalPath=finalPath.resolveSibling(finalPath.getFileName()+".hestia-backup");Path temporary=finalPath.resolveSibling(finalPath.getFileName()+".tmp");Path stage=null;try{Files.createDirectories(finalPath.getParent());Files.deleteIfExists(temporary);stage=Files.createTempDirectory(paths.temporaryDirectory(),"backup-");Path database=stage.resolve("database/hestia.db");Files.createDirectories(database.getParent());snapshot(database);long household=profiles.findDefaultHouseholdId();List<BackupManifest.BackupFile>attachmentFiles=new ArrayList<>();for(String key:attachments.storageKeys(household)){Path source=storage.resolve(key);if(!Files.isRegularFile(source))throw new ValidationException("Há um anexo ausente. Verifique a integridade antes do backup.");Path target=stage.resolve("attachments").resolve(key).normalize();requireInside(stage,target);Files.createDirectories(target.getParent());Files.copy(source,target);attachmentFiles.add(entry(stage,target));}List<BackupManifest.BackupFile>files=List.of(entry(stage,database));int schema=schemaVersion(database);BackupManifest manifest=new BackupManifest(FORMAT_VERSION,"0.1.0",schema,Instant.now(clock),household,"database/hestia.db",List.copyOf(attachmentFiles),files);Path manifestFile=stage.resolve("manifest.json");json.writerWithDefaultPrettyPrinter().writeValue(manifestFile.toFile(),manifest);ZipFile zip=password!=null&&password.length>0?new ZipFile(temporary.toFile(),password):new ZipFile(temporary.toFile());for(Path file:listFiles(stage)){ZipParameters parameters=new ZipParameters();parameters.setFileNameInZip(stage.relativize(file).toString().replace('\\','/'));parameters.setCompressionMethod(CompressionMethod.DEFLATE);if(password!=null&&password.length>0){parameters.setEncryptFiles(true);parameters.setEncryptionMethod(EncryptionMethod.AES);parameters.setAesKeyStrength(AesKeyStrength.KEY_STRENGTH_256);}zip.addFile(file.toFile(),parameters);}validateArchive(temporary,password,false);Files.move(temporary,finalPath,StandardCopyOption.REPLACE_EXISTING,StandardCopyOption.ATOMIC_MOVE);return finalPath;}catch(Exception e){try{Files.deleteIfExists(temporary);}catch(IOException ignored){}if(e instanceof RuntimeException runtime)throw runtime;throw new ValidationException("Não foi possível criar o backup.");}finally{deleteTree(stage);}}
 public void restore(Path backup,char[] password){Path extracted=null,old=null;try{validateArchive(backup,password,true);extracted=Files.createTempDirectory(paths.temporaryDirectory(),"restore-");extractSafely(backup,password,extracted);BackupManifest manifest=readAndValidate(extracted);Path database=extracted.resolve(manifest.databaseFilename()).normalize();validateDatabase(database);Path safety=paths.backupsDirectory().resolve("pre-restore-"+stamp()+".hestia-backup");create(safety,null);old=Files.createTempDirectory(paths.temporaryDirectory(),"previous-");Path oldDb=old.resolve("hestia.db");Files.copy(paths.databaseFile(),oldDb);Path oldAttachments=old.resolve("attachments");copyTree(paths.attachmentsDirectory(),oldAttachments);try{Files.copy(database,paths.databaseFile(),StandardCopyOption.REPLACE_EXISTING);replaceAttachments(extracted.resolve("attachments"));Path settings=extracted.resolve("config/backup.properties");if(Files.exists(settings)){Files.createDirectories(preferences.file().getParent());Files.copy(settings,preferences.file(),StandardCopyOption.REPLACE_EXISTING);}}catch(Exception apply){Files.copy(oldDb,paths.databaseFile(),StandardCopyOption.REPLACE_EXISTING);replaceAttachments(oldAttachments);throw apply;}}catch(Exception e){if(e instanceof RuntimeException runtime)throw runtime;throw new ValidationException("A restauração falhou; os dados anteriores foram preservados.");}finally{deleteTree(extracted);deleteTree(old);}}
 public BackupManifest inspect(Path backup,char[] password){Path extracted=null;try{validateArchive(backup,password,true);extracted=Files.createTempDirectory(paths.temporaryDirectory(),"inspect-");extractSafely(backup,password,extracted);return readAndValidate(extracted);}catch(Exception e){if(e instanceof RuntimeException runtime)throw runtime;throw new ValidationException("Backup inválido ou senha incorreta.");}finally{deleteTree(extracted);}}
 public void runAutomaticIfDue(){var s=preferences.load();if(!s.enabled()||s.directory().isBlank())return;LocalDate last=s.lastBackup()==null?null:LocalDate.ofInstant(s.lastBackup(),clock.getZone());if(LocalDate.now(clock).equals(last))return;CompletableFuture.runAsync(()->{try{Path dir=Path.of(s.directory());create(dir.resolve("hestia-auto-"+stamp()+".hestia-backup"),null);retain(dir,s.retention());preferences.save(new BackupPreferencesService.Settings(true,s.directory(),s.retention(),Instant.now(clock),"Concluído"));}catch(Exception e){preferences.save(new BackupPreferencesService.Settings(true,s.directory(),s.retention(),Instant.now(clock),"Falhou"));}});}
 private void snapshot(Path destination)throws SQLException{try(var c=connections.openConnection();var s=c.prepareStatement("VACUUM INTO ?")){s.setString(1,destination.toString());s.execute();}validateDatabase(destination);}
 private void validateDatabase(Path db)throws SQLException{try(var c=DriverManager.getConnection("jdbc:sqlite:"+db.toAbsolutePath());var r=c.createStatement().executeQuery("PRAGMA integrity_check")){if(!r.next()||!"ok".equalsIgnoreCase(r.getString(1)))throw new ValidationException("O banco do backup não passou na verificação de integridade.");int version=schemaVersion(db);if(version>4)throw new ValidationException("O backup utiliza um esquema mais novo e incompatível.");}}
 private int schemaVersion(Path db)throws SQLException{try(var c=DriverManager.getConnection("jdbc:sqlite:"+db.toAbsolutePath());var r=c.createStatement().executeQuery("SELECT COALESCE(MAX(version),0) FROM schema_history")){return r.getInt(1);}}
 private BackupManifest readAndValidate(Path root)throws Exception{Path manifestPath=root.resolve("manifest.json");if(!Files.isRegularFile(manifestPath))throw new ValidationException("Manifesto ausente.");BackupManifest m=json.readValue(manifestPath.toFile(),BackupManifest.class);if(m.formatVersion()!=FORMAT_VERSION)throw new ValidationException("Versão de backup não suportada.");List<BackupManifest.BackupFile>all=new ArrayList<>(m.files());all.addAll(m.attachments());for(var f:all){Path path=root.resolve(f.path()).normalize();requireInside(root,path);if(!Files.isRegularFile(path)||Files.size(path)!=f.size()||!hashes.sha256(path).equals(f.sha256()))throw new ValidationException("O backup está incompleto ou foi alterado.");}validateDatabase(root.resolve(m.databaseFilename()));return m;}
 private void validateArchive(Path archive,char[] password,boolean requireExtension)throws Exception{if(archive==null||!Files.isRegularFile(archive)||(requireExtension&&!archive.getFileName().toString().endsWith(".hestia-backup")))throw new ValidationException("Selecione um arquivo .hestia-backup válido.");ZipFile zip=password==null?new ZipFile(archive.toFile()):new ZipFile(archive.toFile(),password);if(!zip.isValidZipFile())throw new ValidationException("O arquivo não é um backup válido.");if(zip.getFileHeaders().size()>10000)throw new ValidationException("O backup contém arquivos demais.");long total=0;for(FileHeader h:zip.getFileHeaders()){String name=h.getFileName().replace('\\','/');if(name.startsWith("/")||name.matches("^[A-Za-z]:.*")||name.contains("../")||h.isDirectory()&&name.equals(".."))throw new ValidationException("O backup contém caminhos inseguros.");if(h.getUncompressedSize()>100L*1024*1024)throw new ValidationException("O backup contém um arquivo excessivamente grande.");total=Math.addExact(total,h.getUncompressedSize());if(total>1024L*1024*1024)throw new ValidationException("O backup excede o tamanho permitido.");}}
 private void extractSafely(Path archive,char[] password,Path target)throws Exception{ZipFile zip=password==null?new ZipFile(archive.toFile()):new ZipFile(archive.toFile(),password);validateArchive(archive,password,false);zip.extractAll(target.toString());try(Stream<Path>s=Files.walk(target)){s.forEach(p->requireInside(target,p));}}
 private void retain(Path directory,int keep)throws IOException{try(Stream<Path>s=Files.list(directory)){var files=s.filter(p->p.getFileName().toString().startsWith("hestia-auto-")&&p.getFileName().toString().endsWith(".hestia-backup")).sorted(Comparator.comparingLong(this::modified).reversed()).toList();for(int i=Math.max(1,keep);i<files.size();i++)Files.deleteIfExists(files.get(i));}}
 private long modified(Path p){try{return Files.getLastModifiedTime(p).toMillis();}catch(IOException e){return 0;}}private BackupManifest.BackupFile entry(Path root,Path file)throws IOException{return new BackupManifest.BackupFile(root.relativize(file).toString().replace('\\','/'),Files.size(file),hashes.sha256(file));}private List<Path>listFiles(Path root)throws IOException{try(Stream<Path>s=Files.walk(root)){return s.filter(Files::isRegularFile).toList();}}private void requireInside(Path root,Path path){if(!path.toAbsolutePath().normalize().startsWith(root.toAbsolutePath().normalize()))throw new ValidationException("Caminho inseguro no backup.");}private String stamp(){return DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss").withZone(clock.getZone()).format(Instant.now(clock));}
 private void replaceAttachments(Path source)throws IOException{deleteTree(paths.attachmentsDirectory());Files.createDirectories(paths.attachmentsDirectory());copyTree(source,paths.attachmentsDirectory());}private void copyTree(Path source,Path target)throws IOException{if(source==null||!Files.exists(source))return;try(Stream<Path>s=Files.walk(source)){for(Path p:s.toList()){Path dest=target.resolve(source.relativize(p));if(Files.isDirectory(p))Files.createDirectories(dest);else Files.copy(p,dest,StandardCopyOption.REPLACE_EXISTING);}}}private void deleteTree(Path root){if(root==null||!Files.exists(root))return;try(Stream<Path>s=Files.walk(root)){for(Path p:s.sorted(Comparator.reverseOrder()).toList())Files.deleteIfExists(p);}catch(IOException ignored){}}
}
