package io.github.ryanoviski.hestia.infrastructure.repositories;

import io.github.ryanoviski.hestia.application.dto.AttachmentFilter;
import io.github.ryanoviski.hestia.application.repositories.AttachmentRepository;
import io.github.ryanoviski.hestia.domain.enums.*;
import io.github.ryanoviski.hestia.domain.models.Attachment;
import io.github.ryanoviski.hestia.infrastructure.database.*;
import java.sql.*;import java.time.Instant;import java.util.*;

public final class SqliteAttachmentRepository implements AttachmentRepository {
 private static final String SELECT="""
   SELECT a.*,p.name profile_name,t.description transaction_description,t.transaction_type,
   COALESCE(a.profile_id,t.profile_id) related_profile_id
   FROM attachments a LEFT JOIN transactions t ON t.id=a.transaction_id
   LEFT JOIN profiles p ON p.id=COALESCE(a.profile_id,t.profile_id)
   """;private final ConnectionFactory connections;public SqliteAttachmentRepository(ConnectionFactory c){connections=c;}
 @Override public Attachment insert(Attachment a){String sql="""
   INSERT INTO attachments(household_id,transaction_id,profile_id,document_type,description,original_filename,storage_key,media_type,file_extension,size_bytes,sha256,created_at,updated_at)
   VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)
   """;try(var c=connections.openConnection();var s=c.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS)){int i=1;s.setLong(i++,a.householdId());nullable(s,i++,a.transactionId());nullable(s,i++,a.profileId());s.setString(i++,a.documentType().name());s.setString(i++,a.description());s.setString(i++,a.originalFilename());s.setString(i++,a.storageKey());s.setString(i++,a.mediaType());s.setString(i++,a.fileExtension());s.setLong(i++,a.sizeBytes());s.setString(i++,a.sha256());s.setString(i++,a.createdAt().toString());s.setString(i,a.updatedAt().toString());s.executeUpdate();try(var k=s.getGeneratedKeys()){if(!k.next())throw new SQLException("No attachment id");return new Attachment(k.getLong(1),a.householdId(),a.transactionId(),a.profileId(),a.documentType(),a.description(),a.originalFilename(),a.storageKey(),a.mediaType(),a.fileExtension(),a.sizeBytes(),a.sha256(),a.createdAt(),a.updatedAt(),a.profileName(),a.transactionDescription(),a.transactionType(),a.integrity());}}catch(SQLException e){throw failure("insert attachment",e);}}
 @Override public Optional<Attachment> findById(long household,long id){try(var c=connections.openConnection();var s=c.prepareStatement(SELECT+" WHERE a.household_id=? AND a.id=?")){s.setLong(1,household);s.setLong(2,id);try(var r=s.executeQuery()){return r.next()?Optional.of(map(r)):Optional.empty();}}catch(SQLException e){throw failure("find attachment",e);}}
 @Override public List<Attachment> search(long household,AttachmentFilter f){StringBuilder sql=new StringBuilder(SELECT+" WHERE a.household_id=?");List<Object>v=new ArrayList<>();v.add(household);if(f.name()!=null&&!f.name().isBlank()){sql.append(" AND lower(a.original_filename) LIKE lower(?)");v.add("%"+f.name().trim()+"%");}if(f.profileId()!=null){sql.append(" AND COALESCE(a.profile_id,t.profile_id)=?");v.add(f.profileId());}if(f.documentType()!=null){sql.append(" AND a.document_type=?");v.add(f.documentType().name());}if(f.transactionType()!=null){sql.append(" AND t.transaction_type=?");v.add(f.transactionType().name());}if(f.from()!=null){sql.append(" AND a.created_at>=?");v.add(f.from()+"T00:00:00Z");}if(f.to()!=null){sql.append(" AND a.created_at<?");v.add(f.to().plusDays(1)+"T00:00:00Z");}if(f.transactionTarget()!=null)sql.append(f.transactionTarget()?" AND a.transaction_id IS NOT NULL":" AND a.profile_id IS NOT NULL");sql.append(" ORDER BY a.created_at DESC,a.id DESC");try(var c=connections.openConnection();var s=c.prepareStatement(sql.toString())){bind(s,v);try(var r=s.executeQuery()){List<Attachment>out=new ArrayList<>();while(r.next())out.add(map(r));return out;}}catch(SQLException e){throw failure("search attachments",e);}}
 @Override public void delete(long household,long id){try(var c=connections.openConnection();var s=c.prepareStatement("DELETE FROM attachments WHERE household_id=? AND id=?")){s.setLong(1,household);s.setLong(2,id);if(s.executeUpdate()!=1)throw new SQLException("Attachment not found");}catch(SQLException e){throw failure("delete attachment",e);}}
 @Override public List<String> storageKeys(long household){try(var c=connections.openConnection();var s=c.prepareStatement("SELECT storage_key FROM attachments WHERE household_id=?")){s.setLong(1,household);try(var r=s.executeQuery()){List<String>out=new ArrayList<>();while(r.next())out.add(r.getString(1));return out;}}catch(SQLException e){throw failure("list attachment keys",e);}}
 private Attachment map(ResultSet r)throws SQLException{return new Attachment(r.getLong("id"),r.getLong("household_id"),number(r,"transaction_id"),number(r,"profile_id"),DocumentType.valueOf(r.getString("document_type")),r.getString("description"),r.getString("original_filename"),r.getString("storage_key"),r.getString("media_type"),r.getString("file_extension"),r.getLong("size_bytes"),r.getString("sha256"),Instant.parse(r.getString("created_at")),Instant.parse(r.getString("updated_at")),r.getString("profile_name"),r.getString("transaction_description"),r.getString("transaction_type"),AttachmentIntegrity.AVAILABLE);}
 private Long number(ResultSet r,String n)throws SQLException{long v=r.getLong(n);return r.wasNull()?null:v;}private void nullable(PreparedStatement s,int i,Long v)throws SQLException{if(v==null)s.setNull(i,Types.INTEGER);else s.setLong(i,v);}private void bind(PreparedStatement s,List<Object>v)throws SQLException{int i=1;for(Object x:v){if(x instanceof Long l)s.setLong(i++,l);else s.setString(i++,x.toString());}}private DatabaseException failure(String action,SQLException e){return new DatabaseException("Could not "+action,e);}
}
